name: Deploy React Vite App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to DockerHub (set secrets for DockerHub username and password)
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t react-vite-app:latest .

      # Push Docker image to DockerHub
      - name: Push Docker image
        run: |
          docker tag react-vite-app:latest ${{ secrets.DOCKER_USERNAME }}/react-vite-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/react-vite-app:latest

      # Deploy to EC2
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
           sudo docker pull ${{ secrets.DOCKER_USERNAME }}/react-vite-app:latest
            sudo docker stop react-vite-app || true
            sudo docker rm react-vite-app || true
            sudo docker run -d -p 80:80 --name react-vite-app ${{ secrets.DOCKER_USERNAME }}/react-vite-app:latest
