name: Deploy Vite React Application

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}     

      - name: Build Docker Image
        run: docker build -t accenousntegrals/olw-frontend --build-arg VITE_NODE_ENV='production' --build-arg VITE_SERVER_BASE_URL='${{ secrets.VITE_SERVER_BASE_URL }}' .

      - name: Publish Image to Docker Hub
        run: docker push accenousntegrals/olw-frontend:latest 
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from Docker Hub
        run: docker pull accenousntegrals/olw-frontend:latest 

      - name: Delete Old Container
        run: docker rm -f reactjs-app-container || true  

      - name: Run Docker Container
        run: docker run -d -p 443:443 --name reactjs-app-container accenousntegrals/olw-frontend
