name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t yourusername/frontend:$GITHUB_SHA .
          docker push yourusername/frontend:$GITHUB_SHA

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} ec2-user@${{ secrets.EC2_IP }} << 'EOF'
            docker pull yourusername/frontend:$GITHUB_SHA
            docker stop frontend || true
            docker rm frontend || true
            docker run -d --name frontend -p 3000:3000 yourusername/frontend:$GITHUB_SHA
          EOF
